# No org field (skip Dashboard login)
service: nodejs-api

frameworkVersion: '4'   # recommended if you're using Serverless v4

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGODB_URI: 'mongodb+srv://db_username:db_password@aws-lambda.fm3hq.mongodb.net/?retryWrites=true&w=majority&appName=aws-lambda'

plugins:
  - serverless-offline

functions:
  testConnection:
    handler: handler.testConnection
    events:
      - http:
          path: test
          method: get

  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post

  getUser:
    handler: handler.getUser
    events:
      - http:
          path: users/{id}
          method: get

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete

# add these two lines to completely opt-out of serverless dashboard
org: null
app: null
